In [1]:
#import libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

#import dataset
ds=pd.read_csv ('NB_computer.csv')
ds.head()

Age  income student Credit rating buys computer (Y/N)
0        youth    high      no          fair                  no
1        youth    high      no     excellent                  no
2  middle aged    high      no          fair                 yes
3       senior  medium      no          fair                 yes
4       senior     low     yes          fair                 yes

In [2]:
ds.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 14 entries, 0 to 13
Data columns (total 5 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   Age                  14 non-null     object
 1   income               14 non-null     object
 2   student              14 non-null     object
 3   Credit rating        14 non-null     object
 4   buys computer (Y/N)  14 non-null     object
dtypes: object(5)
memory usage: 688.0+ bytes


In [3]:
x=ds.iloc[:,:-1].values
y=ds.iloc [:,4].values
#case ni taknak split train n test sbb data sikit nnti jadi no accuracy.

In [4]:
#set is to get unique data, then make it into list follow by sort
#after sort, data in sequence 0,1,2
i=0
for i in range(0,4):
    d=list(set(ds.iloc[:, i].values))
    d.sort()
    print(i,d)
    i=i+1

0 ['middle aged', 'senior', 'youth']
1 ['high', 'low', 'medium']
2 ['no', 'yes']
3 ['excellent', 'fair']


In [5]:
#Handling or Encode categorical variables
from sklearn.preprocessing import LabelEncoder
labelencoder_x= LabelEncoder()
x[:, 0] =labelencoder_x.fit_transform(x[:,0])
x[:, 1] =labelencoder_x.fit_transform(x[:,1])
x[:, 2] =labelencoder_x.fit_transform(x[:,2])
x[:, 3] =labelencoder_x.fit_transform(x[:,3])
print(x)
#lepas print baru kita boleh identify, 0,1,2 tu merujuk kepada mana, refer to original table

[[2 0 0 1]
 [2 0 0 0]
 [0 0 0 1]
 [1 2 0 1]
 [1 1 1 1]
 [1 1 1 0]
 [0 1 1 0]
 [2 2 0 1]
 [2 1 1 1]
 [1 2 1 1]
 [2 2 1 0]
 [0 2 0 0]
 [0 0 1 1]
 [1 2 0 0]]


In [6]:
#splitting the dataset into training and test sets
from sklearn.model_selection import train_test_split
x_train , x_test , y_train , y_test = train_test_split (x, y, test_size = 0.2, random_state =0)

In [7]:
#STEP 3
#fitting Naïve Bayes Classifier to the dataset
#we dont use GaussianNB
from sklearn.naive_bayes import BernoulliNB
classifier=BernoulliNB()
classifier=classifier.fit(x,y)

In [8]:
#Preidct the test set results
y_pred=classifier.predict(x_test)
y_test, y_pred

(array(['yes', 'yes', 'yes'], dtype=object),
 array(['yes', 'yes', 'yes'], dtype='<U3'))

In [10]:
#STEP 4
#Predict using classifier
#Predict a person that (Age=youth, Income=medium, student =yes, credit rating = fair) will buy a computer or not.
prediction=classifier.predict ([[2., 2., 1., 1.]])
print(prediction)

['yes']


Conclusion: A person will buy a computer.